<<<<<<< HEAD
# Generated by Django 4.0.6 on 2024-06-21 13:27
=======
# Generated by Django 4.2.11 on 2024-07-20 12:24
>>>>>>> f6e3a5dd36ba209af6ff0803cfa4d0cb316891fc

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('token', models.TextField(verbose_name='Access Token')),
                ('expires_in', models.DateField(verbose_name='Expires In')),
            ],
        ),
    ]
