# Generated by Django 4.2.11 on 2024-08-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_accesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=250, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('api_link', models.URLField(max_length=500, verbose_name='API URL')),
                ('api_admin', models.CharField(max_length=400, verbose_name='Admin Username')),
                ('api_password', models.CharField(max_length=400, verbose_name='Admin Password')),
            ],
        ),
    ]
