# Generated by Django 4.2.11 on 2024-08-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_freeserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeserver',
            name='renovation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Renovation Field'),
        ),
    ]
