# Generated by Django 4.2.11 on 2024-08-10 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vault', '0004_freeserver_renovation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='users',
            field=models.ManyToManyField(related_name='access_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freeserver',
            name='users',
            field=models.ManyToManyField(related_name='free_server', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sshconfig',
            name='users',
            field=models.ManyToManyField(related_name='ssh_configs', to=settings.AUTH_USER_MODEL),
        ),
    ]
